var Url = {
    register: "/frontRegister",
    login: "/frontLogin",
    forgetCheck: "/frontForgetCheck",
    updatePassword: "/frontUpdatePassword",
    initAddress:'/initAddress',
    add_address: "/add_address",  //添加收货地址
    getGoods: "/getGoods",
    getGoodsDetail: "/getGoodsDetail",
    getCollectGoods: "/getCollectGoods",
    initCollectGoodsStatus: "/initCollectGoodsStatus",
    addBuyCar: "/addBuyCar",
    initBuyCar: "/initBuyCar",
    updateBuyCarCount: "/updateBuyCarCount",
    deleteBuyCarGoods: "/deleteBuyCarGoods",
    initTuijian: "/initTuijian",
    lowPrice:"/lowPrice",
    boyCloth:'/boyCloth',
    girlCloth:"/girlCloth",
    suit:"/suit",
    start:'/start',
    gravida:"/gravida",
    boy:"/boy",
    girl:"/girl",
    children:"/children",
    payForToOrder:"/payForToOrder",
    updateDefaultAddress:"/updateDefaultAddress",
    getOrderList:"/getOrderList",
    cancelOrder:"/cancelOrder",
    toCollect:"/toCollect",
    toVisited:"/toVisited",
    insertVisited:"/insertVisited",
    applyBackMoney:"/applyBackMoney",
    signIn:"/signIn",
    cancelPayFor:"/cancelPayFor",
    getDiffOrderStatusNum:"/getDiffOrderStatusNum",
    isExistCoupon:"/isExistCoupon",
    getCoupon:"/getCoupon" ,
    useCoupon:"/useCoupon",
    getConponList:"/getConponList",
    getSigninDetail:"/getSigninDetail",
    getEvaluateDetailInfo:"/getEvaluateDetailInfo",
    insertEvalueInfoToDatabase:"/insertEvalueInfoToDatabase",
    setAuditLog:"/setAuditLog",
    editUserInfo:"/editUserInfo", // 编辑用户信息
    getUserInfoInEditUserPage:"/getUserInfoInEditUserPage",
    search:"/search"
  }

  module.exports = Url;